name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: add repo for g++ 10
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - name: update repos
      run: sudo apt update
    - name: install g++ 10
      run: sudo apt install gcc-10 g++-10
    - name: make g++ 10 default
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
    - name: install UnitTest++
      run: sudo apt install libunittest++-dev
    - name: make
      run: source tbb2020/bin/tbbvars.sh intel64 && make -j all test
    - name: run test
      run: source tbb2020/bin/tbbvars.sh intel64 && bin/test
